[package]
name = "myopic"
version = "0.1.0"
authors = ["nsmryan <nsmryan@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/nsmryan/myopic"

[dependencies]

[dev-dependencies]
criterion = "*"

[[bench]]
name = "bench"
harness = false
